<?php
/**
 * Created by PhpStorm.
 * User: jia
 * Date: 2017/8/24
 * Time: 21:03
 */
namespace app\index\controller;

use think\Controller;

class Base extends Controller{

    /**
     * 初始化
     */
    public function _initialize()
    {
        //父类的
        parent::_initialize(); // TODO: Change the autogenerated stub
        //栏目
        $cateData=$this->getCateData();
        $this->assign('cateData',$cateData);
        //标签
        $tagData=$this->getTagData();
        $this->assign('tagData',$tagData);
        //热门点击
        $clickData=$this->hotClick();
        $this->assign('clickData',$clickData);
        //推荐阅读
        $readData=$this->read();
        $this->assign('readData',$readData);
    }

    /**
     * 查询所有栏目
     */
    public function getCateData(){
        //查询所有栏目
        $cateData=db('cate')->select();
        return $cateData;
    }

    /**
     * 查询所有标签
     */
    public function getTagData(){
        $tagData=db('tags')->select();
        return $tagData;
    }

    /**
     * 热门点击
     */
    private function hotClick(){
        //查询四条标题，按点击量降序排序desc
        $clickData=db('article')->field('id,title')->order('click desc')->limit(4)->select();
        return $clickData;
    }

    /**
     *推荐阅读
     */
    private function read(){
        //查询四条有推荐的文章的标题，
        $readData=db('article')->field('id,title')->where(['state'=>1])->order('id desc')->limit(4)->select();
        return $readData;
    }
}